In [9]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import mean_squared_error,mean_absolute_error,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
house=fetch_california_housing()
df = pd.DataFrame(house['data'], columns=house['feature_names'])
df['MedHouseVal'] = house['target']
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [7]:
y=df['MedHouseVal']
x=df.drop(['AveBedrms','MedHouseVal'],axis=1)
x

       MedInc  HouseAge  AveRooms  Population  AveOccup  Latitude  Longitude
0      8.3252      41.0  6.984127       322.0  2.555556     37.88    -122.23
1      8.3014      21.0  6.238137      2401.0  2.109842     37.86    -122.22
2      7.2574      52.0  8.288136       496.0  2.802260     37.85    -122.24
3      5.6431      52.0  5.817352       558.0  2.547945     37.85    -122.25
4      3.8462      52.0  6.281853       565.0  2.181467     37.85    -122.25
...       ...       ...       ...         ...       ...       ...        ...
20635  1.5603      25.0  5.045455       845.0  2.560606     39.48    -121.09
20636  2.5568      18.0  6.114035       356.0  3.122807     39.49    -121.21
20637  1.7000      17.0  5.205543      1007.0  2.325635     39.43    -121.22
20638  1.8672      18.0  5.329513       741.0  2.123209     39.43    -121.32
20639  2.3886      16.0  5.254717      1387.0  2.616981     39.37    -121.24

[20640 rows x 7 columns]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

In [12]:
print(f'linear model MSE = {mse} , MAE = {mae}')

linear model MSE = 0.5473264990498136 , MAE = 0.5425438932554485